export const PRODUCTS = [
  {
    id: "1",
    title: "Case Explorer wanted",
    image: "/assets/img/8-1.png",
    regularPrice: 12.0,
    salePrice: 8.99,
    tags: ["best choice"],
    inStock: true,
    slug: "case-explorer-wanted",
  },
  {
    id: "2",
    title: "Gaming Headset Pro",
    image: "/assets/img/8-1.png",
    regularPrice: 89.99,
    salePrice: 69.99,
    tags: ["hot"],
    inStock: true,
    slug: "gaming-headset-pro",
  },
  {
    id: "3",
    title: "Wireless Keyboard RGB",
    image: "/assets/img/8-1.png",
    regularPrice: 59.99,
    salePrice: 59.99,
    tags: ["new"],
    inStock: true,
    slug: "wireless-keyboard-rgb",
  },
  {
    id: "4",
    title: 'Ultra HD Monitor 27"',
    image: "/assets/img/8-1.png",
    regularPrice: 299.99,
    salePrice: 249.99,
    tags: ["sale"],
    inStock: true,
    slug: "ultra-hd-monitor-27",
  },
  {
    id: "5",
    title: "Gaming Mouse 16000 DPI",
    image: "/assets/img/8-1.png",
    regularPrice: 49.99,
    salePrice: 39.99,
    tags: [],
    inStock: true,
    slug: "gaming-mouse-16000dpi",
  },
  {
    id: "6",
    title: "Mechanical Keyboard Red Switches",
    image: "/assets/img/8-1.png",
    regularPrice: 129.99,
    salePrice: 99.99,
    tags: ["hot", "sale"],
    inStock: false,
    slug: "mechanical-keyboard-red-switches",
  },
  {
    id: "7",
    title: "Mechanical Keyboard Red Switches",
    image: "/assets/img/8-1.png",
    regularPrice: 129.99,
    salePrice: 99.99,
    tags: ["hot", "sale"],
    inStock: false,
    slug: "mechanical-keyboard-red-switches",
  },
];